{{- range $scaleDown := .Values.scaleActions.scaleDowns }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ $scaleDown.name }}"
  namespace: {{ include "cronjob-scaler.namespace" $ }}
  labels:
    {{- include "cronjob-scaler.labels" $ | nindent 4 }}
spec:
  schedule: "{{ $scaleDown.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "cronjob-scaler.labels" $ | nindent 12 }}
        spec:
          serviceAccountName: "{{ $.Values.serviceAccountName }}"
          serviceAccount: "{{ $.Values.serviceAccountName }}"
          restartPolicy: Never
          containers:
          - name: "{{ $scaleDown.name }}"
            image: registry.redhat.io/openshift4/ose-cli:latest
            command:
            - /bin/sh
            - -c
            - |
                set -e
            {{- range $component := $scaleDown.components }}
                oc patch {{ $component.resourceType }}/{{ $component.name }} --type='json' -p='[{"op": "replace", "path": "/spec/replicas", "value": {{ $component.replicas }} }]'
            {{- end }}
                set +e
{{ end }}
