---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-scaler
  namespace: {{ include "cronjob-scaler.namespace" . }}
  labels:
    {{- include "cronjob-scaler.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cronjob-scaler
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps", "extensions"]
  resources: ["deploymentconfigs", "deployments", "statefulsets"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cronjob-scaler
subjects:
- kind: ServiceAccount
  name: cronjob-scaler
  namespace: {{ include "cronjob-scaler.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cronjob-scaler
